### ISSUE TITLE
Publish 0.10 podspec to Cocoapods spec repo

### ISSUE THREAD

**Issue by mac-cain13** [neilpa/Rex#109]
The 0.10 version of the cocoapod is not yet published to the Cocoapods repo: https://cocoapods.org/pods/Rex

Could the maintainer of the pod publish this new version so we can easily upgrade to it? Would be nice, thanks in advance!

**Comment by bjarkehs** [comment]
Yeah, I'll sort it out now.

**Comment by bjarkehs** [comment]
The podspec does not currently lint. A fixed version is in PR: #110 
I will push to trunk if all travis returns is the same deprecation warning as I was receiving locally.

**Comment by bjarkehs** [comment]
New podspec has been pushed. This can safely be closed. There is however a deprecation warning, but will be fixed in next version of Rex.

**Comment by mac-cain13** [comment]
Thanks!
