### ISSUE TITLE
EXC_BAD_ACCESS when using rex_enabled with <~ operator

### ISSUE THREAD

**Issue by aloco** [neilpa/Rex#128]
Hi,

trying to bind an `AnyProperty<Bool>` to a `UIButton.rex_enabled` by using `<~` and experienced `EXC_BAD_ACCESS`. I played around and it seems that this also crashes when only accessing `UIButton.rex_enabled`

initial Code:

```
    override func viewDidLoad() {
        loginButton.rex_enabled <~ loginViewModel.validCredentials
        super.viewDidLoad()
    }
```

this crashes also:

```
    override func viewDidLoad() {
        loginButton.rex_enabled
        super.viewDidLoad()
    }
```

loginButton comes from an `@IBOutlet` and I can confirm that there is no issue with the button instance.

Do I miss anything here or is this a bug?

```
ReactiveCocoa 4.2.0
Rex 0.10.0
Result 2.0.0
xCode 7.3.1
```

**Comment by RuiAAPeres** [comment]
Can you show the entire crash information? I am pretty sure the issue is not related to Rex.

**Comment by aloco** [comment]
![screen shot 2016-06-08 at 12 42 30](https://cloud.githubusercontent.com/assets/11661125/15891855/e546025a-2d76-11e6-866e-5373881be92e.png)

This one is from the last call (`0_swift_retain`)

![screen shot 2016-06-08 at 12 46 22](https://cloud.githubusercontent.com/assets/11661125/15891880/09ac9b9a-2d77-11e6-9387-40325e07bb53.png)

Do you need anything more?

**Comment by iv-mexx** [comment]
I've experienced similar crashes yesterday when accessing any `rex_...` MutableProperty.

After a time I found that it worked fine when I included the source files directly into my project instead of the framework.

Finally, just rebuilding the Framework with `carthage build` fixed the problem for me.

**Comment by aloco** [comment]
Hi, tried that, but rebuilding from `carthage` doesn´t help. 
Anyway I got another output where `EXC_BAD_ACCESS` happens:
![screen shot 2016-06-08 at 16 12 32](https://cloud.githubusercontent.com/assets/11661125/15898441/a581f166-2d98-11e6-998f-ab91a59fb3dc.png)

Haven´t tried to add the source files of `ReactiveCocoa` directly into my project.

**Comment by neilpa** [comment]
Ugh, since you got a similar crash in `startWithSignal` this feels an awful lot like a swift compiler bug.

**Comment by minuscorp** [comment]
I'm having similar issues with every `rex_` operator. Just using Rex with Carthage.

**Comment by neilpa** [comment]
Can you try bootstrapping carthage with  `--no-use-binaries`?

**Comment by minuscorp** [comment]
It works!

**Comment by neilpa** [comment]
Ok, there must've been an ABI level change with the compiler used to build RAC 4.2. The Rex 0.10 binaries were built in the RAC 4.1 timeframe on an older toolchain.

I'll try and cut a new release this weekend.

**Comment by tcurdt** [comment]
I've run into the same problem. Upgrading Rex fixed this for me too.
I can guess the issue can be closed then?
