### ISSUE TITLE
rex_text or UITextField is not called when it is cleared

### ISSUE THREAD

**Issue by Igor-Palaguta** [neilpa/Rex#129]
rex_text filters nil values, so it does not send any value when text is erased in UITextField

**Comment by neilpa** [comment]
Resolving #125 should cover this as well, right?

**Comment by dmcrodrigues** [comment]
This should be fixed with #133.

**Comment by Igor-Palaguta** [comment]
Not sure that it is fixed, UITextField still returns not optional text, filtering nil values

**Comment by dmcrodrigues** [comment]
You're correct. I included this change in #119.
