### ISSUE TITLE
Incompatible RAC 4.2.1 with Rex 0.10.0

### ISSUE THREAD

**Issue by FranDepascuali** [neilpa/Rex#131]
Hello! With the last release of RAC (4.2.1) and Rex(0.10.0), I get the following error:
`/Carthage/Checkouts/Rex/Source/SignalProducer.swift:84:23: error: ambiguous use of 'debounce(_:onScheduler:)'`

I've solved it by fixing RAC version in 4.2.0

```
github "ReactiveCocoa/ReactiveCocoa" == 4.2.0
github "neilpa/Rex" ~> 0.10.0
```

Maybe you could make a new release to be compatible with 4.2.1? Thank you!

**Comment by RuiAAPeres** [comment]
This has been solved here #130
