### ISSUE TITLE
Transfer ownership to RACCommunity

### ISSUE THREAD

**Issue by neilpa** [neilpa/Rex#135]
I'm not currently doing iOS development in my day job and as a result haven't been able to maintain this library to the degree I would like. There's been discussions about moving Rex under the ReactiveCocoa org and it effectively becoming RAC5 since it provides the missing Swift Cocoa bindings. IMO, moving to RACCommunity would be a good first step in that transition. It'll ease the maintenance burden I haven't kept up with and provide a staging area to prep for the RAC5 transition.

/cc @RuiAAPeres @mdiep @RACCommunity

**Comment by bjarkehs** [comment]
Honestly I think this is a solid decision. It'll ease the burden of maintenance, and may provide even more bindings due to being more visible.

**Comment by RuiAAPeres** [comment]
I am happy with that @neilpa. 👍

**Comment by neilpa** [comment]
Alright, I'm going to make the transfer then. Then we can cut the `0.11` release from the new repo as well.

**Comment by neilpa** [comment]
Travis may need to be setup again but I'm not sure since I've never transferred a repo before.

**Comment by neilpa** [comment]
Transfer complete.
