### ISSUE TITLE
Update bundle name

### ISSUE THREAD

**Issue by neilpa** [neilpa/Rex#136]
Should we update the bundle name from `me.neilpa` now that the repo is under RACCommunity?

**Comment by mdiep** [comment]
If you're okay with leaving it as-is, I'd prefer to do that. We'll hopefully have Rex migrated into RAC in the next ~3 months.

**Comment by neilpa** [comment]
Fine by me. I wasn't sure if it even should be changed since technically they're supposed to be immutable. Although I imagine it doesn't matter in practice for libraries since they get included directly in projects and aren't actually shared.
