### ISSUE TITLE
Release version 0.11

### ISSUE THREAD

**Issue by neilpa** [neilpa/Rex#138]
Cut a `0.11` release targeting RAC 4.2 (or 4.2.1?). I think @RuiAAPeres deserves the honors if he wants it.

**Comment by RuiAAPeres** [comment]
😊😊😊 thanks Neil, will do it first thing in the morning. ❤️

**Comment by dmcrodrigues** [comment]
This closes #128.

**Comment by aschuch** [comment]
`0.11` has been released, so I guess this issue can be closed.
