### ISSUE TITLE
Release a version that supports Swift 2.3

### ISSUE THREAD

**Issue by aschuch** [neilpa/Rex#156]
I have successfully built Rex with Swift 2.3 based on 6243fc56e02f8dad0cdbcfbb8ecdb8b5bf45c9f7.
Would it be possible to release a new version?

**Comment by mdiep** [comment]
@RuiAAPeres?

**Comment by RuiAAPeres** [comment]
@aschuch definitely. Sorry for the delay, I have been away from OS in general, I will take care of it.

**Comment by RuiAAPeres** [comment]
@aschuch https://github.com/RACCommunity/Rex/releases/tag/0.12.0

**Comment by aschuch** [comment]
@RuiAAPeres Awesome, thanks :)
