### ISSUE TITLE
Support for ReactiveSwift

### ISSUE THREAD

**Issue by gkaimakas** [neilpa/Rex#157]
Does Rex support ReactiveSwift and if so how can I use it?

**Comment by RuiAAPeres** [comment]
We are still using a couple of things from the objc counter part (e.g:`rac_willDeallocSignal`). It could make sense to remove this dependencies.

**Comment by mdiep** [comment]
Rex hasn't been updated for Swift 3 yet. But the code from Rex will be a part of RAC 5. It's not ready yet, but it's in the works.

**Comment by dev4dev** [comment]
@mdiep what's the best solution for connecting UIKit and ReactiveSwift for the moment?

**Comment by mdiep** [comment]
You can use the code in [this PR](https://github.com/ReactiveCocoa/ReactiveCocoa/pull/3210), but I can't guarantee that there won't be breaking changes.

We'll hopefully have it merged and an RAC alpha released in the next few days.
