### ISSUE TITLE
Integer overflows when converted from 'Builtin.Int32' to 'Builtin.Int8'

### ISSUE THREAD

**Issue by bjarkehs** [neilpa/Rex#21]
Hi,

Just wanted to say that there is a bug or something in the compiler, which makes the compiler throw a warning when using StaticString.stringValue. This can be avoided by using string interpolation instead, as described here: https://github.com/CocoaLumberjack/CocoaLumberjack/issues/471 (which refers to this StackOverflow: http://stackoverflow.com/questions/25867546/swift-warning-integer-overflows-when-converted-from-builtin-int32-to-builti)

**Comment by neilpa** [comment]
Thanks for the heads up (and the workaround). I'd just been ignoring that for the moment since it seemed to work regardless.
