### ISSUE TITLE
How does one use rex_pressed?

### ISSUE THREAD

**Issue by avalanched** [neilpa/Rex#25]
I'm not sure how i can use rex_pressed, since its value is a CocoaAction

I made my own extension to receive events on a TouchUpInside

```
extension UIButton {

    public var rac_press: Signal<UIButton,NoError> {
        return associatedObject(self, &press, { _ in

            let action = Action<UIButton,UIButton,NoError>{ input in
                SignalProducer(value: input)
            }

            self.addTarget(action.unsafeCocoaAction, action: CocoaAction.selector, forControlEvents: .TouchUpInside)

            return action.values
        })
    }
}

private var press: UInt8 = 0
```

Does this makes sense? or do i misinterpret your rex_pressed?

**Comment by neilpa** [comment]
The idea for `rex_pressed

**Comment by neilpa** [comment]
It's used to bind `Action`s exposed from other objects to button presses. Generally, you don't care _which_ button an action is bound to, only that it's executed when pressed. It's defined as a `CocoaAction` to make it easier to "inject" input to the underlying action if needed.

There's a decent example [here](https://github.com/neilpa/circulate/blob/c9db2bac26edcb6b8b2eb289a0ccc81e880e1b99/Example/DeviceScreen.swift#L79-L87) from another project of mine. (This was before I renamed it to `rex_pressed`).

**Comment by avalanched** [comment]
Thank you for the explanation, this makes much more sense now.
Now I see that my example makes it to limiting.
