### ISSUE TITLE
More Cocoa extensions

### ISSUE THREAD

**Issue by neilpa** [neilpa/Rex#37]
Currently I've been adding things as needed but there's a lot in RAC 2 that should be ported.

**Comment by skyylex** [comment]
@neilpa, I want to help with this. Could you provide some sort of the TODO list?

**Comment by neilpa** [comment]
@skyylex I don't have a TODO list per-se, but there's a lot of [RAC 2 extension methods](https://github.com/ReactiveCocoa/ReactiveCocoa/tree/master/ReactiveCocoa/Objective-C) without Swift equivalents. If there's things you've created for other projects using RAC I would start there and generalize if that makes sense

**Comment by skyylex** [comment]
@neilpa, I got your idea. I have one question according to this. As I see most of the RAC 2 implementations were based on the objc runtime, especially on the rac_signalForSelector which is widely used in almost all of the UIKit extensions. Have you any considerations about how to avoid using of such objc-related mechanisms?

**Comment by neilpa** [comment]
Using the obj-c runtime directly isn't a problem. Swift is built on it and the current Cocoa extensions use it. Look at them, especially how the associated objects are attached. My concern is relying on RAC 2, e.g. `rac_signalForSelector`, `RACSignal`, etc. Anything that has a delegate interface or supports KVO should be pretty easy.

**Comment by neilpa** [comment]
Lets just file more specific ideas going forward.
