### ISSUE TITLE
Need Cartfile that points on ReactiveCocoa swift2 branch

### ISSUE THREAD

**Issue by larryonoff** [neilpa/Rex#45]
Could you please do separate e.g. branch?

**Comment by neilpa** [comment]
You mean newer than the [current pre-release](https://github.com/neilpa/Rex/releases/tag/v0.8.0) targeting the RAC 4 alpha? There's some additional updates that'll be needed before it can track the head of the RAC `swift2` branch.

**Comment by larryonoff** [comment]
I cannot build "via carthage" Rex and RAC, since Rex requires RAC 4.0 when my configuration needs swift2 branch.

**Comment by neilpa** [comment]
I recommend not using the branch head while we're in this state of churn. Pick a commit/release and use that, then explicitly update to new commits as they're available. Targeting the `swift2` branch explicitly is problematic because it can break anytime RAC is updated. See also #31.

**Comment by larryonoff** [comment]
Sure. I don't frighten breaking changes :)

**Comment by neilpa** [comment]
Then you'll have to fork Rex if you really need to track the `swift2` head. I'm not going to commit to a branch that tracks RAC that closely. It's too easy for it to break out from under me and may take time before I fix it. Then we'll have situations like #31 which I want to avoid going forward.

**Comment by larryonoff** [comment]
Thanks for support. Got the idea.
