### ISSUE TITLE
New tag for RAC 4 alpha 3

### ISSUE THREAD

**Issue by bjarkehs** [neilpa/Rex#57]
Hi,

Would you be willing to create a new tag for the alpha 3 so that it can be easily targeted? Or should I assume that 0.9.0-alpha.2 would be good enough?

**Comment by bjarkehs** [comment]
Nevermind, I'm just blind. Never open an issue before coffee.

**Comment by bjarkehs** [comment]
It threw me off that they're the only tags not following the format "vX.Y.Z"

**Comment by neilpa** [comment]
I added new tags and updated the release to match the other style
