### ISSUE TITLE
carthage bootstrap NSInvalidArgumentException

### ISSUE THREAD

**Issue by finneycanhelp** [neilpa/Rex#63]
Using master, both "carthage bootstrap" and "carthage update" both yield the error:

```
uncaught exception 'NSInvalidArgumentException', reason: 'working directory doesn't exist.' 
```

It looks similar to https://github.com/Carthage/Carthage/issues/745 However, changing the Cartfile to different things didn't help. 

The Rex Cartfile is identical to something I am using for a private project and it works fine there. So, something deeper is happening here.

**Comment by ikesyo** [comment]
I think this would be fixed by https://github.com/Carthage/Carthage/pull/925.
