### ISSUE TITLE
Generic print method

### ISSUE THREAD

**Issue by larryonoff** [neilpa/Rex#9]
I'm going to write more generic print method, but don't know what to do with `.Next` and `.Error`. I cannot just call `signal |> print(.Next)` or `signal |> print(.Error)`. These cases need to be called with arguments. Could you please help? Should I implement additional enum?

See the actual code below.

``` swift
public func print<T, E>(_ event: Event<T, E>? = nil)(signal: SignalProducer<T, E>) -> SignalProducer<T, E> {
    return signal
        |> on(event: { aEvent in
            if let event = event {
                switch (aEvent, event) {
                case (.Next, .Next):
                    println(aEvent)

                case (.Error, .Error):
                    println(aEvent)

                case (.Completed, .Completed):
                    println(aEvent)

                case (.Interrupted, .Interrupted):
                    println(aEvent)

                default:
                    break
                }
            } else {
                println(aEvent)
            }
        })
}
```

**Comment by neilpa** [comment]
I don't see the value here over the existing `printNext` and `printError`, especially since it can't be done without a secondary custom enum to act as the filter. Yes it's a bit tedious if we also want `printCompleted` and `printInterrupted` but I'd prefer that over something like `enum EventFilter` that mirrors `Event`.

**Comment by larryonoff** [comment]
My idea of generic method is connected with RAC `flatten` and `flatMap` signatures. I would like to follow RAC approach and conventions.

**Comment by neilpa** [comment]
Those functions are the exception and not the rule. They are defined in that way so consumers make a conscience decision about how inner signals should be flattened. In the previous versions of RAC most people blindly chose `flattenMap` without realizing `concat` or `switchToLatest` were available for signals-of-signals. (cf ReactiveCocoa/ReactiveCocoa#1768)
