### ISSUE TITLE
Rex 0.10 missing UIDatePicker.rex_date from framework binaries

### ISSUE THREAD

**Issue by jmper1** [neilpa/Rex#96]
I wanted to create a PR for this. But I cloned the repository and checked if the related file (Source/UIKit/UIDatePicker.swift) is included in the iOS framework target. Alas, it is! Now I'm at a loss why the UIDatePicker extension is not included in the generated header file for Rex. Any ideas?

**Comment by neilpa** [comment]
I must've attached an old binary to the release. I'll build a new one.

**Comment by neilpa** [comment]
New version uploaded.

**Comment by jmper1** [comment]
Thanks! Will double-check.

**Comment by jmper1** [comment]
Yup, that did the trick! Closing now...
